// font-box.js
class FontBox extends HTMLElement {
  connectedCallback() {
    const name = this.getAttribute('font-family') || 'Sans-serif';
    this.innerHTML = ` <div style="font-family: '${name}', Arial, sans-serif;" class="font-box-wrapper">
    <h3>${name}</h3>
    <span style="font-style: italic; font-weight: 100;">Dit is 100</span>
    <span style="font-style: italic; font-weight: 200;">Dit is 200</span>
    <span style="font-style: italic; font-weight: 300;">Dit is 300</span>
    <span style="font-style: italic; font-weight: 400;">Dit is 400</span>
    <span style="font-style: italic; font-weight: 500;">Dit is 500</span>
    <span style="font-style: italic; font-weight: 600;">Dit is 600</span>
    <span style="font-style: italic; font-weight: 700;">Dit is 700</span>
    <span style="font-style: italic; font-weight: 800;">Dit is 800</span>
    <span style="font-style: italic; font-weight: 900;">Dit is 900</span>
    <p style="font-weight:100">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:200">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:300">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:400">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:500">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:600">Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Nam a ligula vel mauris commodo bibendum id nec est. Sed fringilla finibus euismod. Donec interdum elementum est, a eleifend dolor sollicitudin iaculis. Phasellus dapibus congue eros, eget maximus dui viverra eu. Mauris pharetra nulla eleifend tincidunt rutrum. Sed porta, lacus eget rutrum vulputate, orci augue sodales purus, eu sagittis felis magna ac urna. Vestibulum et metus et ex aliquet pellentesque. Maecenas id tellus quis magna maximus egestas eget non enim. Phasellus quis felis sit amet erat condimentum finibus. Donec leo nisi, molestie et maximus in, molestie vitae massa. Praesent quis bibendum neque, a volutpat sem. Aenean in urna finibus, pellentesque ante vel, lobortis tortor. Vestibulum porta felis tristique risus pretium, mollis tempus ligula ultrices. Proin tempus ligula at dictum facilisis. Aenean pharetra, arcu in luctus mattis, magna lectus accumsan velit, id porttitor quam lorem ut leo.</p>
    <p style="font-weight:700">Dit is 700</p>
    <p style="font-weight:800">Dit is 800</p>
    <p style="font-weight:900">Dit is 900</p>
  </div>`;
  }
}

customElements.define('font-box', FontBox);